name: payment-ci

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags


jobs:
  test:
    defaults:
      run:
        working-directory: go/src/github.com/microservices-demo/payment
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos 
      COMMIT: ${{ github.sha }}
      REPO: payment
      GKE_CLUSTER: ic-backstage-demo    
      GKE_ZONE: asia-south1
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/sock-shop-payment
      GO_VERSION: 1.7
      GOPATH: /home/runner/work/payment/payment/go/
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/github.com/microservices-demo/payment


    #
    #
    # Set up go
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }} # The Go version to download (if necessary) and use.

    #
    #
    # Install prereqs
    - name: Install prereqs
      run: |
        go get -u github.com/mattn/goveralls
        go get -u github.com/FiloSottile/gvt
        gvt restore

    #
    #
    # Container build step
    - name: Build
      env:
        DOCKER_BUILDKIT: 1
      run: ./scripts/build.sh

    #
    #
    # Unit test step
    - name: Unit test
      env:
        DOCKER_BUILDKIT: 1
      run: ./test/test.sh unit.py

    #
    #
    # Container test step
    # - name: Container test
    #   env:
    #     DOCKER_BUILDKIT: 1
    #   run: ./test/test.sh container.py --tag ${{ env.COMMIT }}

    #
    #
    # Submit coveralls
    # - name: Submit Coveralls
    #   env:
    #     COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: goveralls -coverprofile=coverage.out -service=github

    
    - name: Login gcloud
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        
    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Tag Docker image
      run: docker tag $GROUP/payment:$COMMIT  $IMAGE_NAME:$COMMIT
      
    - name: Push Docker image
      run: docker push $IMAGE_NAME:$COMMIT
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/develop'
      
    - name: Configure GKE credentials
      run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
  
    - name: Deploy application
      run:  helm upgrade paytment ./deploy/helm-chart-payment --install --set image.tag=$COMMIT -n sock-shop
