# Default values for sock-shop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: gcr.io/omni-163105/sock-shop-payments
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: "402a21307810b33cfe1e0f3bd4abfb3ef8a5f3bd"

imagePullSecrets: []
  # - name: gcr

java:
  options: -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
zipkin: 
  enabled:  false
  url: zipkin.zipkin.svc.cluster.local
frontend:
  replicas: 1
loadtest:
  replicas: 2
  enabled: false
